### PR TITLE
Add NewReal1-Bb index

### PR DESCRIPTION
**Pull request by strk**
It took me the whole morning to extract from:

99f2d4fb6e25fca77a753e86430098a1  TheNewRealBookVol1-Bb.pdf (md5sum)

### CODE REVIEW

**Comment by strk** [comment]
I'm pretty fast with keyboard and "vi" editor :)
How I did:
 1. Started from the C version index (which seems good)
 2. Run an extractor (the nodejs one)
 3. Iteratively checked which piece was the first non-matching title and "offsetted" all the lines from there onward to the desired page number

To help with the iterations I wrote a short perl script "offset.pl" that took a single argument (a signed offset) and would change both starting and ending pages by summing up that offset.

Common reasons for page mismatches:
  1. Pages with photos of musicians were not in my PDF
  2. Some pieces were single page instead of multipages

Please include the md5sum of your source PDF when you contribute the updated index.

**Comment by aspiers** [comment]
Awesome!  Great idea about checksums too.  We should incorporate checksums into the repo, allowing for the fact that the same real book could have multiple PDFs.

**Comment by strk** [comment]
And maybe number of pages too, as changes in resolution or reflow would change checksum while keeping number of pages unchanged


On July 10, 2024 9:49:55 PM GMT+02:00, Adam Spiers ***@***.***> wrote:
>Awesome!  Great idea about checksums too.  We should incorporate checksums into the repo, allowing for the fact that the same real book could have multiple PDFs.
>

-- 
Sent from hand-held device with K-9 Mail. Please excuse my brevity.

**Comment by aspiers** [comment]
I'm travelling right now, any chance you could file an issue for those ideas?

**Comment by strk** [comment]
> I'm travelling right now, any chance you could file an issue for those ideas?

https://github.com/aspiers/book-indices/issues/46

**Pull request merged**
