### PR TITLE
Add utility script to apply an offset to book indices

### PR DESCRIPTION
**Pull request by strk**
I wrote this simple perl script to help me out with writing the recent indices.
See https://github.com/aspiers/book-indices/pull/42#issuecomment-2220523572

### CODE REVIEW

**Comment by aspiers** [comment]
Thanks!  This seems useful and I can see the value in having it within this repo, but it really needs documentation so that it's clear what it does and how to use it.  Please could you add that first?

**Comment by strk** [comment]
Where would you want to see that documentation ? Usage is printed if you invoke it with no args: https://github.com/aspiers/book-indices/blob/faa0c18a9ce191a0d3cc98d6f73dfdd1ad408f92/utils/offset.pl#L6

**Comment by aspiers** [comment]
I saw that usage text, but it doesn't cover:

- what the utility does
- what the offset is
- how to use it (e.g. what are the inputs and outputs)

I suggest documenting it either in comments at the top of the script, or in a new `utils/README.md`.

**Comment by strk** [comment]
On Sat, Jul 13, 2024 at 08:22:23AM -0700, Adam Spiers wrote:
> I saw that usage text, but it doesn't cover:
> 
> - what the utility does
> - what the offset is
> - how to use it (e.g. what are the inputs and outputs)
> 
> I suggest documenting it either in comments at the top of the script, or in a new `utils/README.md`.

Done with comment on top of the file

**Review by aspiers — APPROVED** [review]

**Pull request merged**
